on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: cachix/install-nix-action@v7
      - name: Get release notes
        id: release-notes
        run: |
          escape() { perl -p -e 's/%/%25/;s/\r/%0D/;s/\n/%0A/'; }
          ref=${{ github.ref }}
          tag_name=${ref#refs/tags/}
          release_name=$(git tag -l --format='%(subject)' "$tag_name"  | escape)
          body=$(git tag -l --format='%(contents:body)' "$tag_name" | escape)

          echo "::set-output name=release_name::$release_name"
          echo "::set-output name=body::$body"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: "${{ steps.release-notes.outputs.release_name }}"
          body: "${{ steps.release-notes.outputs.body }}"
          draft: true
          prerelease: false
      - run: |
          mkdir -p build
          cd build
          nix run nixpkgs.gox -c gox ..
          gzip *
      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: build/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
