name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
    - run:
        nix-build
    - run:
        nix-shell --pure --run "NIX_SSL_CERT_FILE=$NIX_SSL_CERT_FILE go test"
    - run:
        nix run nixpkgs.gox -c gox -os '!windows' .
