name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
    - run:
        nix-build
    - run:
        nix-shell --run './test/test.sh'
    - run:
        nix run nixpkgs.gox -c gox .
