name: "Test"
on:
  pull_request:
  push:
  schedule:
    - cron:  '31 2 * * *'
jobs:
  tests:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        nix: [ legacy, flakes ]
        exclude:
          # flakes installer broken atm
          - os: macos-latest
            nix: flakes
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Install legacy nix
      uses: cachix/install-nix-action@v13
      if: matrix.nix == 'legacy'
    - name: Install flakes nix
      uses: cachix/install-nix-action@v13
      if: matrix.nix == 'flakes'
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20201007_5257a25/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - run:
        nix-build -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixpkgs-unstable.tar.gz
    - run:
        nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixpkgs-unstable.tar.gz --pure --run "TEST_ASSETS=$(pwd)/test NIX_SSL_CERT_FILE=$NIX_SSL_CERT_FILE go test"
      # tests rely on `--store`, which is not supported on macOS
      if: matrix.os == 'ubuntu-latest'
    - run:
        nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixpkgs-unstable.tar.gz --pure -p gox -p go --run "gox -os '!windows' -osarch '!darwin/386' ."
      # no need to run this on multiple platforms
      if: matrix.os == 'ubuntu-latest' && matrix.nix == 'flakes'
